FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Expose the port your app runs on
EXPOSE 80

# Define the command to start the application
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
