version: '3.9'
name: varcan

services:
  frontend:
    extends:
      file: ../../docker-compose.base.yml
      service: app-base
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      net:
        ipv4_address: 172.28.1.7


networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/28
          gateway: 172.28.1.1
